_target_: src.logger.CometMLWriter
project_name: lensless_imaging
workspace: null
run_name: modular_prepost
mode: online
loss_names: ["loss", "mse", "lpips_loss"]
log_checkpoints: False
id_length: 32
